sudo: required
services:
  - docker

before_install:
  - docker build -t lacampe/docker-react -f Dockerfile.dev .

script:
  - docker run lacampe/docker-react yarn run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-208801103360'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
